=== Processoriented/popm/Deploy/xml/NavigationSettings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<!--definiton of Id type-->
  <xs:simpleType name="recidtype">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{3}"/>
    </xs:restriction>
</xs:simpleType>
  
<!-- definition of attributes -->
<xs:attribute name="enabled" type="xs:boolean"/>
<xs:attribute name="collapsed" type="xs:boolean"/>
<xs:attribute name="ordinal" type="xs:positiveInteger"/>
<xs:attribute name="recId" type="recidtype"/>
<xs:attribute name="gID" type="xs:string"/>
<xs:attribute name="srtDir" type="xs:string"/>
<xs:attribute name="luElem" type="xs:string"/>
<xs:attribute name="recListVisible" type="xs:boolean"/>
<xs:attribute name="luAttr" type="xs:string"/>
  
<!-- definition of simple elements -->
<xs:element name="Name" type="xs:string"/>
<xs:element name="Icon" type="xs:string"/>
<xs:element name ="ReferenceURL" type="xs:string"/>
<xs:element name="RecEle" type="xs:string"/>
<xs:element name="PrimEle" type="xs:string"/>
<xs:element name="SecEle" type="xs:string"/>
<xs:element name="TerEle" type="xs:string"/>
<xs:element name="FilterEle" type="xs:string"/>
<xs:element name="SortEle" type="xs:string"/>
<xs:element name="Description" type="xs:string"/>
  

  
<!-- definition of complex elements -->
<xs:element name="GroupEle">
  <xs:complexType>
    <xs:attribute ref="gID" use="required"/>
    <xs:attribute ref="luElem" use="required"/>
    <xs:attribute ref="luAttr" use="required"/>
  </xs:complexType>
</xs:element>

  <xs:element name="ToolView">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="Icon" minOccurs="0" maxOccurs="1"/>
        <xs:element ref ="ReferenceURL" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="RecEle" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="PrimEle" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="SecEle" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="TerEle" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="FilterEle" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="GroupEle" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="SortEle" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute ref="enabled" use="required"/>
      <xs:attribute ref="recId" use="required"/>
      <xs:attribute ref="ordinal"/>
   </xs:complexType>
  </xs:element>

  <xs:element name="NavigationTool">
    <xs:complexType>
      <xs:sequence>
          <xs:element ref="Name" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Icon" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="ToolView" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute ref="enabled" use="required"/>
      <xs:attribute ref="collapsed" use="required"/>
      <xs:attribute ref="recId" use="required"/>
      <xs:attribute ref="ordinal"/>
      <xs:attribute ref="recListVisible" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="NavigationTool" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Processoriented/popm/Deploy/xml/NavigationSettings.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="NavigationSettings.xsd" >

  <NavigationTool enabled="true" collapsed="true" recId="100" ordinal="1" recListVisible="true">
    <Name>Projects</Name>
    <Icon>img/project.svg</Icon>
    <ToolView enabled="true"  recId="101" ordinal="1">
      <Name>Planning</Name>
      <Icon>img/dashboard.svg</Icon>      
    </ToolView>
    <ToolView enabled="true"  recId="102" ordinal="2">
      <Name>Meetings</Name>
      <Icon>img/people.svg</Icon>
    </ToolView>
    <ToolView enabled="true"  recId="103" ordinal="3">
      <Name>Deliverables</Name>
      <Icon>img/file.svg</Icon>
    </ToolView>
    <ToolView enabled="true" ordinal="4" recId="104">
      <Name>Issues</Name>
      <Icon>img/warning.svg</Icon>
      <ReferenceURL>xml/issues.xml</ReferenceURL>
      <RecEle>ROW</RecEle>
      <PrimEle>SC_SYS_DF_FORM_DOC_ID_ACTION</PrimEle>
      <SecEle>SC_DF_FIELD_1</SecEle>
      <TerEle>SC_DF_FIELD_1</TerEle>
      <FilterEle>SC_DF_FIELD_5</FilterEle>
      <GroupEle gID="SC_DF_FIELD_7" luElem="HEADER" luAttr="el_values"></GroupEle>
      <SortEle>SC_DF_FIELD_12</SortEle>
    </ToolView>
    <ToolView enabled="true" ordinal="5" recId="105">
      <Name>Tasks</Name>
      <Icon>img/task.svg</Icon>
    </ToolView>
  </NavigationTool>
  
  <NavigationTool enabled="true" collapsed="true" recId="110" ordinal="2" recListVisible="true">
      <Name>Resources</Name>
      <Icon>img/key.svg</Icon>
    <ToolView enabled="true" recId="111" ordinal="1">
      <Name>People</Name>
      <Icon>img/person.svg</Icon>
    </ToolView>
    <ToolView enabled="true" recId="112" ordinal="2">
      <Name>Places</Name>
      <Icon>img/location.svg</Icon>
    </ToolView>
    <ToolView enabled="true" recId="113" ordinal="3">
      <Name>Things</Name>
      <Icon>img/wrench.svg</Icon>
    </ToolView>
  </NavigationTool>
 
  <NavigationTool enabled="true" collapsed="true" recId="120" ordinal="3" recListVisible="false">
    <Name>Calendar</Name>
    <Icon>img/calendar.svg</Icon>
  </NavigationTool>
 
  <NavigationTool enabled="true" collapsed="true" recId="190" ordinal="99" recListVisible="false">
    <Name>Settings</Name>
    <Icon>img/cog.svg</Icon>
  </NavigationTool>
</root>
